import type { ChatMessage, Game, Score, Session } from "./types";

export const SEED_GAMES: Game[] = [
  {
    id: "11111111-1111-1111-1111-111111111101",
    slug: "tower-to-eternity",
    title: "Tower to Eternity",
    platform: "roblox",
    description:
      "Find the way to reach the Eternity Tower in this speedrun challenge.",
    roblox_universe_id: null,
    roblox_place_id: "74440430260118",
    ordered_datastore_id: "PlayerScores",
    is_vetted: true,
    is_published: true,
    is_featured: true,
    sort_order: 1,
    published_at: new Date().toISOString(),
  },
  {
    id: "11111111-1111-1111-1111-111111111102",
    slug: "warrior-of-light",
    title: "Warrior Of Light",
    platform: "roblox",
    description:
      "Forge legendary gear, unlock hidden power, and defend Yesu's village from shadow creatures.",
    roblox_universe_id: null,
    roblox_place_id: "76414853406395",
    ordered_datastore_id: "PlayerScores",
    is_vetted: true,
    is_published: true,
    is_featured: true,
    sort_order: 2,
    published_at: new Date().toISOString(),
  },
  {
    id: "11111111-1111-1111-1111-111111111103",
    slug: "run-to-the-gate",
    title: "Run to the Gate",
    platform: "roblox",
    description:
      "Follow the path past seven signs and come face to face with the Guy at the Gates.",
    roblox_universe_id: null,
    roblox_place_id: "73387522939923",
    ordered_datastore_id: "PlayerScores",
    is_vetted: true,
    is_published: true,
    is_featured: true,
    sort_order: 3,
    published_at: new Date().toISOString(),
  },
  {
    id: "11111111-1111-1111-1111-111111111104",
    slug: "holodori",
    title: "Holodori",
    platform: "external",
    description:
      "Hololive Dreams — free-to-play rhythm & RPG. Clear songs, train holomems, and expand the Dream Park together.",
    roblox_universe_id: null,
    roblox_place_id: null,
    ordered_datastore_id: null,
    is_vetted: true,
    is_published: true,
    is_featured: false,
    sort_order: 4,
    published_at: new Date().toISOString(),
  },
];

const hoursFromNow = (h: number) =>
  new Date(Date.now() + h * 60 * 60 * 1000).toISOString();

export const SEED_SESSIONS: Session[] = [
  {
    id: "22222222-2222-2222-2222-222222222201",
    game_id: SEED_GAMES[0].id,
    creator_id: null,
    title: "Friday Night Speedrun Jam",
    starts_at: hoursFromNow(6),
    capacity: 40,
    registered_count: 24,
    locale: "en",
    creator: null,
    game: {
      title: "Tower to Eternity",
      slug: "tower-to-eternity",
      platform: "roblox",
    },
  },
  {
    id: "22222222-2222-2222-2222-222222222202",
    game_id: SEED_GAMES[1].id,
    creator_id: null,
    title: "Weekend Defense Squad",
    starts_at: hoursFromNow(30),
    capacity: 32,
    registered_count: 31,
    locale: "en",
    creator: null,
    game: {
      title: "Warrior Of Light",
      slug: "warrior-of-light",
      platform: "roblox",
    },
  },
  {
    id: "22222222-2222-2222-2222-222222222203",
    game_id: SEED_GAMES[2].id,
    creator_id: null,
    title: "Run to the Gate Co-op Night",
    starts_at: hoursFromNow(54),
    capacity: 40,
    registered_count: 12,
    locale: "en",
    creator: null,
    game: {
      title: "Run to the Gate",
      slug: "run-to-the-gate",
      platform: "roblox",
    },
  },
  {
    id: "22222222-2222-2222-2222-222222222204",
    game_id: SEED_GAMES[3].id,
    creator_id: null,
    title: "Holodori Park Night",
    starts_at: hoursFromNow(4),
    capacity: 24,
    registered_count: 11,
    locale: "en",
    creator: null,
    game: {
      title: "Hololive Dreams",
      slug: "holodori",
      platform: "external",
    },
  },
  {
    id: "22222222-2222-2222-2222-222222222205",
    game_id: SEED_GAMES[3].id,
    creator_id: null,
    title: "Rhythm Clear Squad",
    starts_at: hoursFromNow(18),
    capacity: 16,
    registered_count: 8,
    locale: "ja",
    creator: null,
    game: {
      title: "Hololive Dreams",
      slug: "holodori",
      platform: "external",
    },
  },
  {
    id: "22222222-2222-2222-2222-222222222206",
    game_id: SEED_GAMES[3].id,
    creator_id: null,
    title: "Holomem Training Hour",
    starts_at: hoursFromNow(42),
    capacity: 20,
    registered_count: 5,
    locale: "en",
    creator: null,
    game: {
      title: "Hololive Dreams",
      slug: "holodori",
      platform: "external",
    },
  },
];

export const SEED_SCORES: Score[] = [
  {
    id: "s1",
    game_id: SEED_GAMES[0].id,
    user_id: null,
    roblox_entry_key: "ferretking12",
    display_name: "ferretking12",
    score: 18420,
    synced_at: null,
    game: { title: "Tower to Eternity", slug: "tower-to-eternity" },
  },
  {
    id: "s2",
    game_id: SEED_GAMES[2].id,
    user_id: null,
    roblox_entry_key: "nova_dev",
    display_name: "nova_dev",
    score: 17955,
    synced_at: null,
    game: { title: "Run to the Gate", slug: "run-to-the-gate" },
  },
  {
    id: "s3",
    game_id: SEED_GAMES[0].id,
    user_id: null,
    roblox_entry_key: "quinnbuilds",
    display_name: "quinnbuilds",
    score: 16210,
    synced_at: null,
    game: { title: "Tower to Eternity", slug: "tower-to-eternity" },
  },
  {
    id: "s4",
    game_id: SEED_GAMES[1].id,
    user_id: null,
    roblox_entry_key: "pixelmage",
    display_name: "pixelmage",
    score: 15880,
    synced_at: null,
    game: { title: "Warrior Of Light", slug: "warrior-of-light" },
  },
  {
    id: "s5",
    game_id: SEED_GAMES[1].id,
    user_id: null,
    roblox_entry_key: "rustyblox",
    display_name: "rustyblox",
    score: 14905,
    synced_at: null,
    game: { title: "Warrior Of Light", slug: "warrior-of-light" },
  },
  {
    id: "s6",
    game_id: SEED_GAMES[2].id,
    user_id: null,
    roblox_entry_key: "lumen.exe",
    display_name: "lumen.exe",
    score: 14220,
    synced_at: null,
    game: { title: "Run to the Gate", slug: "run-to-the-gate" },
  },
  {
    id: "s7",
    game_id: SEED_GAMES[0].id,
    user_id: null,
    roblox_entry_key: "obbyqueen",
    display_name: "obbyqueen",
    score: 13760,
    synced_at: null,
    game: { title: "Tower to Eternity", slug: "tower-to-eternity" },
  },
  {
    id: "s8",
    game_id: SEED_GAMES[1].id,
    user_id: null,
    roblox_entry_key: "tinybuilder",
    display_name: "tinybuilder",
    score: 12995,
    synced_at: null,
    game: { title: "Warrior Of Light", slug: "warrior-of-light" },
  },
];

export const SEED_CHAT: ChatMessage[] = [
  {
    id: "c1",
    channel: "web",
    author: "nova_dev",
    author_discord_id: null,
    author_avatar_url: null,
    author_avatar_decoration_url: null,
    author_badges: [],
    body: "anyone else's obby run keep crashing on the third checkpoint",
    discord_message_id: null,
    source: "discord",
    user_id: null,
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: "c2",
    channel: "web",
    author: "ferretking12",
    author_discord_id: null,
    author_avatar_url: null,
    author_avatar_decoration_url: null,
    author_badges: [],
    body: "yeah, admins pushed a fix — reload the place and it should be gone",
    discord_message_id: null,
    source: "discord",
    user_id: null,
    created_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
  },
  {
    id: "c3",
    channel: "web",
    author: "quinnbuilds",
    author_discord_id: null,
    author_avatar_url: null,
    author_avatar_decoration_url: null,
    author_badges: [],
    body: "friday jam signups close in an hour, get in while you can",
    discord_message_id: null,
    source: "discord",
    user_id: null,
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
];

export const SEED_TICKER = [
  { text: "● KOINA — shared spaces · shared interests · shared purpose", tone: "neutral" as const },
  { text: "▲ JustVibing — play together in the commons", tone: "up" as const },
  { text: "● Oshikatsu — fan space for belonging", tone: "neutral" as const },
  { text: "▼ Barriers down · belonging up", tone: "down" as const },
  { text: "● NUMA — immersive presence, coming soon", tone: "neutral" as const },
  { text: "▲ κοινά — fellowship through shared participation", tone: "up" as const },
  {
    text: "● Inspired by The Digital Collective and the Holy Spirit",
    tone: "neutral" as const,
  },
];
